# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoginFlow' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LoginFlow

  pod 'AEOTPTextField'
  pod 'Alamofire'
  pod 'Toast-Swift', '~> 5.0.1'
  target 'LoginFlowTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LoginFlowUITests' do
    # Pods for testing
  end

end
